apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - namespace.yaml
nameSuffix: -dev
namespace: demo-dev
patches:
  - path: patch-replicas.yaml
images:
  - name: nginxdemos/hello
    newTag: "latest"   # ejemplo: dev usa 'latest'
