apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - namespace.yaml
nameSuffix: -prod
namespace: demo-prod
patches:
  - path: patch-replicas.yaml
images:
  - name: nginxdemos/hello
    newTag: "plain-text"  # prod se queda en tag fijo
