apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-plain
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/galvarado/argocd-lab.git
    targetRevision: main
    path: manifests-plain
  destination:
    server: https://kubernetes.default.svc
    namespace: demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true